version: "3"

services:
    loadbalancer:
      image: nginx:alpine
      container_name: loadbalancer
      restart: unless-stopped
      volumes:
       - ./nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "80:80"

    server1:
      image: nginx:alpine
      container_name: server1
      restart: unless-stopped
      volumes:
       - ./server1.txt:/usr/share/nginx/html/index.html:ro
      ports:
        - "81:80"

    server2:
      image: nginx:alpine
      container_name: server2
      restart: unless-stopped
      volumes:
       - ./server2.txt:/usr/share/nginx/html/index.html:ro
      ports:
        - "82:80"

    server3:
      image: nginx:alpine
      container_name: server3
      restart: unless-stopped
      volumes:
       - ./server3.txt:/usr/share/nginx/html/index.html:ro
      ports:
        - "83:80"

